<?php

/**
 * The default color for event status.
 */
define('EVENT_STATUS_DEFAULT_COLOR', '#FFFFFF');

/**
 * The default css placeholder.
 */
define('EVENT_STATUS_CSS_PLACEHOLDER', 'status_placeholder');

/**
 * Define hooks_preprocess_hook().
 */
function event_calendar_colors_preprocess_calendar_item(&$variables) {
  $event_entity = $variables['item']->getEntity();
  $event_status = \Drupal::entityTypeManager()
    ->getStorage('taxonomy_term')
    ->load($event_entity->get('field_event_status')
      ->first()
      ->getValue()['target_id']);
  //@todo: Attach dynamic event status class to each event.

  // Attach dynamic library to events.
  $variables['#attached']['library'][] = 'event_calendar_colors/event_calendar_colors';
}

/**
 * Implements hook_library_info_alter().
 */
function event_calendar_colors_library_info_alter(&$libraries, $extension) {
  // Adds the css files based on the default event status library.
  $path = file_create_url(file_default_scheme() . "://");

  if (!empty($libraries['event_color_default'])) {
    foreach ($libraries['event_color_default']['css'] as $depth => $files) {
      foreach ($files as $file_name => $file_options) {
        $libraries['event_calendar_colors']['css'][$depth][$path . $file_name] = $file_options;
      }
    }
  }
}
